id: 062b21f186af404ab84ea186c1e51560
title: Toh_283-The_Sutra_of_the_Three_Bodies-v1
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-09-06T15:43:59.689Z'
  creationid: BG
  eft-text-id: UT22084-068-017
  eft-text-version: 2.21.1 2019
  xmlns-eft: http://read.84000.co/ns/1.0
